### PR TITLE
Updates to Coffee Maker support

### PR DESCRIPTION
**Pull request by alexanv1**
This implements updated Coffee Maker support as discussed in https://github.com/simbaja/ha_gehome/issues/62
Water Heater entity is removed and is replaced by the following:
- Start Brewing button entity
- Cancel Brewing button entity
- Start Descaling button entity
- Cancel Descaling button entity
- Brew Strength select entity
- Brew Cups number entity
- Brew Temperature number entity

The last 3 are "virtual" in the sense that the settings are only sent to the device when Start Brewing button is pressed. Their state does update based on changes to the device state (e.g. if brewing is started via the app with different settings).

Here is an example of Lovelace UI that these changes enable:
StartBrewing

One issue I was battling with is that I have the Coffee Maker set to Celsius but want other entities in Home Assistant (climate, etc) as Fahrenheit so my HA default unit is Fahrenheit.
The solution I found is two-fold:
1) Respect device settings in the integration by converting to Celsius if device is set to Celsius and exposing it as a unit of measurement
2) Redefine TEMPERATURE_FAHRENHEIT and TEMPERATURE_CELSIUS constants to use the Unicode values for C and F - this is a bit of a hack but it prevents the automatic conversion that Home Assistant likes to do.

With these 2 changes, I get exactly the behavior I want where Home Assistant units match what I specified in the app for the Coffee Maker. However, I understand if these changes may not be desirable for others (though they only impact those whose device setting doesn't match HA setting) so I am happy to pull them out of the PR and keep that in a fork that I will run with.

### CODE REVIEW

**Comment by simbaja** [comment]
Sorry for the delayed response, finally feeling a bit better.  

Looking through the changes, most of it looks good.  If you could not include the changes related to the temperature unit in this pull, that would be appreciated.  The API is always in Fahrenheit no matter what the device is set to, which causes problems if this type of behavior is incorporated in the base integration (and I've had multiple reports of issues here, which is why the Dev version hardcodes it).  We can probably use a template sensor to meet your needs until HA provides a way to override the global temperature unit of measure on a per-entity basis.

**Comment by alexanv1** [comment]
> Sorry for the delayed response, finally feeling a bit better.
> 
> Looking through the changes, most of it looks good. If you could not include the changes related to the temperature unit in this pull, that would be appreciated. The API is always in Fahrenheit no matter what the device is set to, which causes problems if this type of behavior is incorporated in the base integration (and I've had multiple reports of issues here, which is why the Dev version hardcodes it). We can probably use a template sensor to meet your needs until HA provides a way to override the global temperature unit of measure on a per-entity basis.

Sure, sounds good. I will try to update the PR to remove that in the next day or two.
Template sensors won't do it as there are too many entities to template so it becomes too messy, I will just run a private fork for now. Perhaps, down the road, we can think about some config option for the integration to tweak how the units behave (respect what device is set to and convert vs. always exposing Fahrenheit).

**Comment by simbaja** [comment]
I think the issue is that there's no way to do it right now while still keeping it a "temperature" device since HA will auto convert to the global setting.  There's also jo way to do it consistently, especially for HA controlled devices like water heaters).  They'd need to add some way of preventing auto convert for a device or entity.  I saw some tickets to that effect, but don't think it's something they're really pursuing.

I guess for now a private branch is the best course until they have that :(

**Comment by alexanv1** [comment]
@simbaja, I removed the temperature unit changes. Sorry it took so long :)

**Pull request merged**
